# Generated by Django 4.2.3 on 2023-07-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
