# Generated by Django 4.2.4 on 2023-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='order',
            name='order_completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
