# Generated by Django 4.2.4 on 2023-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_customer_address_order_order_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
